# Generated by Django 3.2.9 on 2021-11-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=16, null=True)),
                ('scope', models.CharField(max_length=16, null=True)),
                ('type', models.CharField(max_length=16, null=True)),
                ('institution', models.CharField(max_length=32, null=True)),
                ('trial', models.CharField(max_length=32, null=True)),
                ('subjects', models.PositiveIntegerField(null=True)),
                ('department', models.CharField(max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clinics',
            },
        ),
    ]
