# Generated by Django 3.2.9 on 2021-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='id',
            field=models.CharField(db_index=True, max_length=16, primary_key=True, serialize=False),
        ),
    ]
